### ISSUE TITLE
Support serde `rename` and `rename_all`

### ISSUE THREAD

**Issue by poly000** [yanganto/toml-example#20]
```rust
#[derive(Deserialize, Serialize,TomlExample)]
#[serde(rename_all = "kebab-case")]
struct Foo {
    a_a: String,
    #[serde(rename = "bb")]
    b: String,
}

println!("{}", Foo::toml_example());
```

expected:
```toml
a-a = ""

bb = ""
```

actual output:
```toml
a_a = ""

b = ""
```
